// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASd9HLSeM1CIhJhGAvI0u5L6MbBS40ZOU',
    appId: '1:665643505189:web:a914a839ecd74a09a311cc',
    messagingSenderId: '665643505189',
    projectId: 'auth-5d87d',
    authDomain: 'auth-5d87d.firebaseapp.com',
    storageBucket: 'auth-5d87d.appspot.com',
    measurementId: 'G-QRVHNCYJER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa_T1fXlCMmdyqYTjEFaSWTsp-lXDmNPE',
    appId: '1:665643505189:android:e7d21744ed3c2b6ba311cc',
    messagingSenderId: '665643505189',
    projectId: 'auth-5d87d',
    storageBucket: 'auth-5d87d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbM6yMZ9zL397NTMlzilkdaPLgv20kE3w',
    appId: '1:665643505189:ios:0dd005f7aee04970a311cc',
    messagingSenderId: '665643505189',
    projectId: 'auth-5d87d',
    storageBucket: 'auth-5d87d.appspot.com',
    iosBundleId: 'com.example.authication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbM6yMZ9zL397NTMlzilkdaPLgv20kE3w',
    appId: '1:665643505189:ios:2e3792cd69f797e5a311cc',
    messagingSenderId: '665643505189',
    projectId: 'auth-5d87d',
    storageBucket: 'auth-5d87d.appspot.com',
    iosBundleId: 'com.example.authication.RunnerTests',
  );
}
